### ISSUE TITLE
Dumper issue

### ISSUE THREAD

**Issue by romancewastaken** [a2x/cs2-dumper#66] opened 2024-02-09 00:21 UTC
The dumper has been automatically closing for me for a few weeks now. The offsets on here are also not updating as fast as they use to it seems. As to the dumper exe crashing, I have no idea why, there isn't a log file, the window closes pretty much right away but does create a generated folder, but no files created.

Edit: also creating a shortcut and adding the flags does not help

**Comment by a2x** [comment] 2024-02-09 01:07
Could you try building the program from source first? (Build in debug mode so there's symbols included)

If the program is returning an `Err` somewhere, try setting the environment variable `RUST_BACKTRACE=full` by running `set RUST_BACKTRACE=full` before running the binary. Once you've done this, copy and paste the stack trace here. This will help me identify the root cause of the error.

E.g.
<img src="https://github.com/a2x/cs2-dumper/assets/45197573/847aaf20-abd2-4ae2-bb2a-ff8fd8ace4da" width="250">
<img src="https://github.com/a2x/cs2-dumper/assets/45197573/08f10049-5420-42dd-993f-badf40eb639f" width="450">

**Comment by romancewastaken** [comment] 2024-02-09 01:55
> Could you try building the program from source first? (Build in debug mode so there's symbols included)
> 
> If the program is returning an `Err` somewhere, try setting the environment variable `RUST_BACKTRACE=full` by running `set RUST_BACKTRACE=full` before running the binary. Once you've done this, copy and paste the stack trace here. This will help me identify the root cause of the error.
> 
> E.g. <img alt="" width="250" src="https://private-user-images.githubusercontent.com/45197573/303524308-847aaf20-abd2-4ae2-bb2a-ff8fd8ace4da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0NDMwODUsIm5iZiI6MTcwNzQ0Mjc4NSwicGF0aCI6Ii80NTE5NzU3My8zMDM1MjQzMDgtODQ3YWFmMjAtYWJkMi00YWUyLWJiMmEtZmY4ZmQ4YWNlNGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDAxMzk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwODUxNTQ2NjAzMTVmODQwN2Y3YTIwMTA3NDI2ZGQxYTdmZGEwYzQyYjJiYWZiYTI5OTllN2E4YjZjMzE0NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hCAxmV0rvh1msMGGjwiIV0QcpQM5pzSeN3qcqjF597Y"> <img alt="" width="450" src="https://private-user-images.githubusercontent.com/45197573/303524652-08f10049-5420-42dd-993f-badf40eb639f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0NDMwODUsIm5iZiI6MTcwNzQ0Mjc4NSwicGF0aCI6Ii80NTE5NzU3My8zMDM1MjQ2NTItMDhmMTAwNDktNTQyMC00MmRkLTk5M2YtYmFkZjQwZWI2MzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDAxMzk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlYWNhMDkxYzFmNWJmZjU4MmUyMDc2ZGJjMjA3OTc5MzYwM2NhZDUzZGIwMzIxN2IyY2VlNjU0NjNhNDEwYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-nOBEOOsY7QHG6EYHnRsIbjM4tVQvLxyHFI-OHpx7tE">

After building and setting backtrace it seems to work even though I assume its literally 1:1 with the release build. Not totally sure why or how but if anyone has a similar issue, try building it yourself (make sure to include the config file)

**Comment by a2x** [comment] 2024-02-09 02:45
Yeah, I'm not sure why that is. I've already updated the latest release with the newest binary + config.json file, which works for me.

**Comment by xCorteX** [comment] 2024-02-10 23:46
why is it that the dumper doesn't copy anything into folder?
dumper is automatically closing...

**Comment by a2x** [comment] 2024-02-12 05:06
Closing for now.

**Closed by a2x** 2024-02-12 05:06 UTC
